apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-argocd
  namespace: openshift-gitops
spec:
  destination:
    name: pacman
  project: demo-project-argocd
  source:
    path: 04.Application-Lifecycle/demo-argocd/mariadb-resources/pacman
    repoURL: https://github.com/michaelkotelnikov/rhacm-workshop
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
